language: android

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - tonymontes@live.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - ANDROID_API=25
    - ANDROID_BUILD_TOOLS=25.0.1

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-24

before_install:
 - chmod +x gradlew
 - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
 - export JAVA_HOME=$JAVA8_HOME

after_success:
 - ./gradlew coveralls

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - cd $TRAVIS_BUILD_DIR/
  - ./gradlew jacocoTestReport

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
